print('----------------------------------------------------------tw:@tek_elo')
print('Bir demet içinde ki elemanlara ulaşmak için\n'
      'bütün liste teknikleri kullanılabilir')
print('---------------------------------------------------------------------')
print()
demet = (0,5,10,15,20,25,30)
print('----------indisle---------------')
print()
print('1.  indise ve 0. elemana ulaşma')
print(demet[0])
print()
print('3. indise ve 2. elemana ulaşma')
print(demet[2])
print()
print('-1 elemana ulaşma')
print(demet[-1])
print()
print('-1 elemana ulaşma')
print(demet[-4])

print('----------Dilimleme teknikleriyle---------------')
print()
print('2. eleman ve sonrasını yazdırma')
print(demet[2:])
print()
print('0. elemandan 4. eleman hariç yazdırma')
print(demet[:4])
print()
print('2. elemandan 4. eleman hariç yazdırma')
print(demet[2:4])
print()
print('bütün elemanları yazdırma')
print(demet[:])
print()
print('bütün elemanları yazdırma')
print(demet[::])
print()
print('demeti ters çevirerek yazdırma')
print(demet[::-1])
print()
print('0. elamndan 2 atlayarak yazırma')
print(demet[::2])
print()
print('1. elamndan 5. eleman hariç 2 atlayarak yazırma')
print(demet[1:5:2])



