import time
print(time.time())
print("-----------------------------")
print(time.ctime())
print("-----------------------------")
print(time.gmtime(time.time()))
print("-----------------------------")
print(time.localtime(time.time()))
print("-----------------------------")
print (time.strftime("%d/%m/%Y"))
print("-----------------------------")
print ("Başlangıç : %s" % time.ctime())
time.sleep( 5 )
print ("Bitiş : %s" % time.ctime())