a=b=c=d=5
print("a:",a)
print("b:",b)
print("c:",c)
print("d:",d)
print("***********************")
a=b=c=d="Konya"
print("a:",a)
print("b:",b)
print("c:",c)
print("d:",d)
print("***********************")
ad, soyAd, meslek, il, no= "Halit", "Kartal","Mimar","Adana",585 #eksik girilirse hata vermez, çıkışta alamazsınız
print(ad)
print(soyAd)
print(meslek)
print(il)
print(no)
print("***********************")
ad ="Adnan"; soyAd="Mert"; meslek="Mühendis"; il="Samsun"; no=56
print(ad)
print(soyAd)
print(meslek)
print(il)
print(no)
