karmasikSayi=3+4j
print(type(karmasikSayi))
print(karmasikSayi)
print("*******************")
karmasikSayiIki=complex(3,5)
print(karmasikSayiIki)
print(type(karmasikSayiIki))
print("*******************")
print("gerçek ve reel kısımları 0 olan sayı tanımlama")
karmasikSayiUc=complex()
print(karmasikSayiUc)
print(type(karmasikSayiUc))
print("*******************")
z=complex(3.3,5.9)
print(z)
print(type(z))