tupleBir= ()
tupleIki=tuple()
tupleUc=(1,2,3,4,5)
tupleDort=("Konya","Yalova","İstanbul")
tupleBes= ((1,2),"Ankara",(3,4,5))

print(tupleBir)
print(type(tupleBir))
print("---------------------")
print(tupleIki)
print(type(tupleIki))
print("---------------------")
print(tupleUc)
print(type(tupleUc))
print("---------------------")
print(tupleDort)
print(type(tupleDort))
print("---------------------")
print(tupleBes)
print(type(tupleBes))