listeBir=[]
listeIki=list()
listeUc=[1,2,3,4,5]
listeDort=["Konya","Yalova","İstanbul"]
listeBes=[[1,2],"Ankara",[3,4,5]]

print(listeBir)
print(type(listeBir))
print("---------------------")
print(listeIki)
print(type(listeIki))
print("---------------------")
print(listeUc)
print(type(listeUc))
print("---------------------")
print(listeDort)
print(type(listeDort))
print("---------------------")
print(listeBes)
print(type(listeBes))