print("Toplama:",4+8+2)
print("***************")
print("Çıkarma:",10-6-2)
print("***************")
print("Çarpma:",3*5)
print("***************")
print("Bölme:",15/3)
print("***************")
print("Bölüm:",9//2)
print("Mod:",9%2)
print("***************")
print("Bölüm:",16//3)
print("Mod:",16%3)
print("***************")
print("Üs alma:",2**3)